"""
Python Lab Tests
CEN3031 Software Engineering 1
Fall 2025

DO NOT EDIT THIS FILE
"""

from app.lab import *
from app.data import students

def test_alice_average():
   avg = calculate_student_average(students, "Alice Johnson")
   assert avg == (88 + 92 + 79 + 85 + 75 + 90) / 6

def test_benjamin_average():
   avg = calculate_student_average(students, "Benjamin Lee")
   assert avg == (76 + 81 + 90) / 3

def test_empty_average():
   avg = calculate_student_average(students, "Empty Student")
   assert avg == 0

def test_extremes():
   (lowest, highest) = lowest_highest_grade(students)
   assert lowest == 67
   assert highest == 100

def test_feedback(capsys):
   print_feedback(students)
   (out, err) = capsys.readouterr()
   assert err == ""
   out_tokens = out.splitlines()
   assert len(out_tokens) == len(FEEDBACK_OUT)
   for i in range(len(out_tokens)):
      assert out_tokens[i] == FEEDBACK_OUT[i]

def test_exam_average():
   average = exam_average(students, "Math Test 1")
   assert average == (88 + 76 + 95 + 67 + 82 + 90 + 100 + 77 + 84 + 69) / 10

FEEDBACK_OUT = [
   "[Alice Johnson] Science Test 1 (79%): Needs improvement in lab work.",
   "[Daniel Kim] Math Test 1 (67%): Needs extra practice with algebra.",
   "[Ella Brown] English Test 1 (79%): Needs better grammar.",
   "[Jack Miller] Math Test 1 (69%): Needs better preparation."
]